<h1 class="testtest">This is my template, there are many like it, but this one is mine.</h1>

<!--<script type="text/javascript">
    requirejs(['Testing_Test/test'],function(test){
        alert("Loaded");
        console.log(test);
    });
</script>
--> <!--This is the another way !!!!!-->
<script type="text/x-magento-init">
       {
        ".testtest":{
            "Testing_Test/test":{}
        }
        }
</script>
